### PR TITLE
proposal to fix axp288 fuel gauge

### PR DESCRIPTION
**Pull request by sfumato77**
enable all axp2xxx module

### CODE REVIEW

**Comment by nicman23** [comment]
@burzumishi can you test this ? my tablet's charger got cut (such shoddy quality) and i cannot test anything :C 

@sfumato77 how well does this work? Also thanks :)

**Comment by sfumato77** [comment]
on my tablet. It works.
I reported it, even on bugzilla.
and they will notice me, and that my "tricksy".
logically it is not "elegant" as a solution, but ...

someone else can replicate ?.
I have news of a failure and a sucess (my).
It needs another

**Comment by burzumishi** [comment]
Hi guys,

I hope you're doing well :)

Excuse me for answering so late, but I've been too busy at work for last months. My flexx's linux is broken at the moment, I do expect to have some free time this week for reinstalling linux on my device and test this pull request.

I would like to thank you for being so active with this repo, publishing that bunch of patches and workarrounds.

**Comment by nicman23** [comment]
@sfumato77 4.11rc1 fixed this right?

**Comment by sfumato77** [comment]
Yes. 4.11rc1 this with my patch and useless and outdated.

**Pull request closed without merging**
